---

- name: "Setup Laptop"
  hosts: all
  roles:
    - role: homebrew
      tags:
       - homebrew
    - role: osx_defaults
      tags:
       - defaults

  tasks:
  - name: Create ~/workdir
    file:
      dest: "~/workdir"
      state: directory
  - name: Create ~/.ssh
    file:
      dest: "~/.ssh"
      state: directory
