---

- name: "Setup Laptop"
  hosts: all

  pre_tasks:
  - name: Install imagemagick 6
    homebrew:
      name: "imagemagick@6"
      state: present
      install_options: "with-ghostscript"

  roles:
    - role: osx_defaults
      tags:
       - defaults
    - role: homebrew
      tags:
       - homebrew

  tasks:
  - name: Create ~/workspace
    file:
      dest: "~/workspace"
      state: directory
  - name: Change default shell to Homebrew Bash
    become: true
    command: chpass -s /usr/local/bin/bash "{{ ansible_ssh_user }}"
    tags:
     - chpass
  - name: Install RVM
    shell: "curl -sSL https://get.rvm.io | bash -s stable"
    tags:
     - rvm
