---
- name: create Xcode dirs
  file: name={{ ansible_env.HOME }}/{{ item }} state=directory
  with_items:
    - 'Library/Developer/Xcode/UserData/FontAndColorThemes'

- name: add Monokai XCode theme
  copy: >
    dest=~/Library/Developer/Xcode/UserData/FontAndColorThemes/Monokai_Revisited.dvtcolortheme
    src=Monokai_Revisited.dvtcolortheme
