---
- name: install pip
  command: >
    /usr/bin/easy_install pip
    creates=/usr/local/bin/pip

- name: install virtualenv
  command: >
    /usr/local/bin/pip install virtualenv
    creates=/usr/local/bin/virtualenv

- name: install Jedi
  pip: name=jedi
  sudo: true
