---

- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- include: homebrew-taps.yml
- include: homebrew-formulas.yml
- include: homebrew-casks.yml
- include: homebrew-fonts.yml

# vim:set ft=ansible:
