---

- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- include: homebrew-taps.yml
- include: homebrew-formulas.yml
- include: homebrew-casks.yml
- include: homebrew-fonts.yml

- name:
  homebrew:
    name: homebrew/dupes/grep
    install_options: with-default-names

# vim:set ft=ansible:
