---

- name: Configure macOS defaults
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    host: "{{ item.host | default(omit) }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items: "{{ defaults }}"
  ignore_errors: true

- name: Defaults | Display login window as name and password
  become: true
  command: defaults write /Library/Preferences/com.apple.loginwindow.plist SHOWFULLNAME -bool true

- name: Defaults | Show volume and Blutooth in menu bar
  command: defaults write com.apple.systemuiserver menuExtras -array "/System/Library/CoreServices/Menu Extras/Clock.menu" "/System/Library/CoreServices/Menu Extras/Battery.menu" "/System/Library/CoreServices/Menu Extras/AirPort.menu" "/System/Library/CoreServices/Menu Extras/Displays.menu" "/System/Library/CoreServices/Menu Extras/Volume.menu" "/System/Library/CoreServices/Menu Extras/Bluetooth.menu"

- name: Defaults | Disable smart quotes
  become: true
  command: defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticQuoteSubstitutionEnabled" -bool false

- name: Defaults | Set ISO8601 AppleFirstWeekday
  become: true
  command: defaults write NSGlobalDomain AppleFirstWeekday -dict "gregorian" -int 1
